### ISSUE TITLE
Stub_chain ties `fixture_parameters_spec.rb` too closely to implementation

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-tools-tester#22]
While upgrading vCloud Tools Tester to use vCloud Core's new `ApiInterface.rb` rather than `Vcloud::Core::Fog::ModelInterface` directly, we found that the `fixture_parameters_spec.rb` was hard to update because it uses [stub_chain](http://apidock.com/rspec/Spec/Mocks/Methods/stub_chain). It looks like to use the API interface we'd have to work out the order of methods called and stub those in order, thus defeating the purpose of having an API interface.

We have left it as is for now, but would like to find a way to test this without tying the test so closely to the exact implementation of vCloud Core fog code and fog code itself.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
