### ISSUE TITLE
Allow override to location of config file

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-tools-tester#25]
At the moment the config file location is hard-coded to a location under spec/integration with no override which would make it easy to accidentally clobber it, e.g. with a `git reset --hard`.

https://github.com/alphagov/vcloud-launcher/commit/c51acf90619fe0274062d785cf20ac6b8894dad2#commitcomment-6319859

At the very least an override should be allowed.

If the location is changed, the Jenkins scripts will have to be updated as well.

This is not a vCloud Tools Tester issue, as that just takes a config file. The issue is one in each of the integration tests and the integration test instructions. However, raising it here it is to do with use of this tool, to avoid unnecessary duplication.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
